name: test workflow with variables

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: step1
        uses: actions/checkout@v2
      
      - name: step1 (Print secret)
        run: |
          echo "Printing"
          echo ${{secrets.MY_NAME}}
          

 
