name: My CI/CD Workflow

on:
  push:
    branches:
      - main

env:   # Define workflow-level environment variables here
      
      MY_WORKFLOW_VARIABLE: This is a workflow-level variable outside!


jobs:
  build:
    runs-on: ubuntu-latest
    
    env:   # Job Env Variable
      
      JOB_VARIABLE: This is a JOB-level variable that is inside the JOB

    steps:
    - name: Create and run step level varibale
     
      run: echo "MY_STEP_VARIABLE=This is a step-level variable"      
    
   
    - name: Print workflow-level variables
      run: |
        echo "Workflow Variable: $MY_WORKFLOW_VARIABLE"
        

    - name: Print JOB-level variables
      run: |
        echo "JOB Variable: $JOB_VARIABLE"
       
