name: test workflow with variables

on: [push]
env:
  college: "Lambton"
  course: "DOCT"

jobs:
  job1:
    runs-on: ubuntu-latest

    
    steps:
      - name: step1
        uses: actions/checkout@v2

      - name: step2
        run: |
          echo "From step2 college and course is"
          echo $college
          echo $course          

      - name: step3
        run: |
          echo "From step3 college and course is"
          echo $college
          echo $course

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step4
        run: |
          echo "From step1 and job2 college and course is"
          echo $college
          echo $course


    

