name: test workflow

on: [push]


jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: step1
        uses: actions/checkout@v2

      - name: step2
        run: |
          echo "Hello world"


