name: My CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:   # Define workflow-level environment variables here
      MY_VARIABLE: my_value
      ANOTHER_VARIABLE: another_value

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print workflow-level variables
      run: |
        echo "MY_VARIABLE: $MY_VARIABLE"
        echo "ANOTHER_VARIABLE: $ANOTHER_VARIABLE"
